main().catch((err) => (console.error(err), process.exit(1)))
export async function main() {
  console.log('yeah')
}
